version: "3.8"

services:
  db:
    image: postgres:15
    container_name: penjadwalan-ev-db
    restart: always
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: EVSchedulingSystem
      TZ: Asia/Jakarta
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d EVSchedulingSystem"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./backend
    container_name: ev-api
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://appuser:secret123@db:5432/EVSchedulingSystem

volumes:
  postgres_data:
